
// Objective-C API for talking to the following Go packages
//
//	bitbucket.org/qdeconinck/quic-traffic/bulk/bulkclient
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Bulkclient_FRAMEWORK_H__
#define __Bulkclient_FRAMEWORK_H__

#include "Bulkclient.objc.h"
#include "Universe.objc.h"

#endif
