
// Objective-C API for talking to the following Go packages
//
//	bitbucket.org/qdeconinck/quic-traffic
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Quictraffic_FRAMEWORK_H__
#define __Quictraffic_FRAMEWORK_H__

#include "Quictraffic.objc.h"
#include "Universe.objc.h"

#endif
