// Objective-C API for talking to bitbucket.org/qdeconinck/quic-traffic Go package.
//   gobind -lang=objc bitbucket.org/qdeconinck/quic-traffic
//
// File is generated by gobind. Do not edit.

#ifndef __Quictraffic_H__
#define __Quictraffic_H__

@import Foundation;
#include "Universe.objc.h"


/**
 * NotifyReachability change for the notifyID
 */
FOUNDATION_EXPORT void QuictrafficNotifyReachability(NSString* notifyID);

/**
 * Run the QUIC traffic experiment
 */
FOUNDATION_EXPORT NSString* QuictrafficRun(NSString* traffic, BOOL cache, long maxPathID, NSString* logFile, NSString* output, NSString* url, NSString* notifyID);

#endif
