// Objective-C API for talking to github.com/lucas-clemente/quic-go/example/client_benchmarker_cached/client Go package.
//   gobind -lang=objc github.com/lucas-clemente/quic-go/example/client_benchmarker_cached/client
//
// File is generated by gobind. Do not edit.

#ifndef __Client_H__
#define __Client_H__

@import Foundation;
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* ClientRun(BOOL verbose, BOOL multipath, NSString* output, NSString* url);

#endif
